interface:
  - port: eth1/51
    description: ansible
    switchport_mode: access
    vlan: 151

    
vlan:
  - number: 151
    name: ansible
    description: ansible
    ip: 172.16.151.1
    subnet_mask: 255.255.255.0

    
ospf:
  - pid: 10
    network:
          - net: 10.100.10.0
            subnetmask: 0.0.0.255
            area: 0
bgp:
  - asn: 65001
    neighbour:
      - address: 172.20.20.0
        remote_as: 65002
